// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commitment.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_commitment_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_commitment_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "crypto-curve/proto_gen/curve_point.pb.switch.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_commitment_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_commitment_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_commitment_2eproto;
namespace safeheron {
namespace proto {
class KGD;
struct KGDDefaultTypeInternal;
extern KGDDefaultTypeInternal _KGD_default_instance_;
class KGD_Num;
struct KGD_NumDefaultTypeInternal;
extern KGD_NumDefaultTypeInternal _KGD_Num_default_instance_;
}  // namespace proto
}  // namespace safeheron
PROTOBUF_NAMESPACE_OPEN
template<> ::safeheron::proto::KGD* Arena::CreateMaybeMessage<::safeheron::proto::KGD>(Arena*);
template<> ::safeheron::proto::KGD_Num* Arena::CreateMaybeMessage<::safeheron::proto::KGD_Num>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace safeheron {
namespace proto {

// ===================================================================

class KGD final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.KGD) */ {
 public:
  inline KGD() : KGD(nullptr) {}
  ~KGD() override;
  explicit PROTOBUF_CONSTEXPR KGD(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  KGD(const KGD& from);
  KGD(KGD&& from) noexcept
    : KGD() {
    *this = ::std::move(from);
  }

  inline KGD& operator=(const KGD& from) {
    CopyFrom(from);
    return *this;
  }
  inline KGD& operator=(KGD&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const KGD& default_instance() {
    return *internal_default_instance();
  }
  static inline const KGD* internal_default_instance() {
    return reinterpret_cast<const KGD*>(
               &_KGD_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(KGD& a, KGD& b) {
    a.Swap(&b);
  }
  inline void Swap(KGD* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(KGD* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  KGD* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<KGD>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const KGD& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const KGD& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KGD* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "safeheron.proto.KGD";
  }
  protected:
  explicit KGD(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBlindFactorFieldNumber = 2,
    kYFieldNumber = 1,
  };
  // string blindFactor = 2;
  void clear_blindfactor();
  const std::string& blindfactor() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_blindfactor(ArgT0&& arg0, ArgT... args);
  std::string* mutable_blindfactor();
  PROTOBUF_NODISCARD std::string* release_blindfactor();
  void set_allocated_blindfactor(std::string* blindfactor);
  private:
  const std::string& _internal_blindfactor() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_blindfactor(const std::string& value);
  std::string* _internal_mutable_blindfactor();
  public:

  // .safeheron.proto.CurvePoint y = 1;
  bool has_y() const;
  private:
  bool _internal_has_y() const;
  public:
  void clear_y();
  const ::safeheron::proto::CurvePoint& y() const;
  PROTOBUF_NODISCARD ::safeheron::proto::CurvePoint* release_y();
  ::safeheron::proto::CurvePoint* mutable_y();
  void set_allocated_y(::safeheron::proto::CurvePoint* y);
  private:
  const ::safeheron::proto::CurvePoint& _internal_y() const;
  ::safeheron::proto::CurvePoint* _internal_mutable_y();
  public:
  void unsafe_arena_set_allocated_y(
      ::safeheron::proto::CurvePoint* y);
  ::safeheron::proto::CurvePoint* unsafe_arena_release_y();

  // @@protoc_insertion_point(class_scope:safeheron.proto.KGD)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr blindfactor_;
  ::safeheron::proto::CurvePoint* y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_commitment_2eproto;
};
// -------------------------------------------------------------------

class KGD_Num final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.KGD_Num) */ {
 public:
  inline KGD_Num() : KGD_Num(nullptr) {}
  ~KGD_Num() override;
  explicit PROTOBUF_CONSTEXPR KGD_Num(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  KGD_Num(const KGD_Num& from);
  KGD_Num(KGD_Num&& from) noexcept
    : KGD_Num() {
    *this = ::std::move(from);
  }

  inline KGD_Num& operator=(const KGD_Num& from) {
    CopyFrom(from);
    return *this;
  }
  inline KGD_Num& operator=(KGD_Num&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const KGD_Num& default_instance() {
    return *internal_default_instance();
  }
  static inline const KGD_Num* internal_default_instance() {
    return reinterpret_cast<const KGD_Num*>(
               &_KGD_Num_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(KGD_Num& a, KGD_Num& b) {
    a.Swap(&b);
  }
  inline void Swap(KGD_Num* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(KGD_Num* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  KGD_Num* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<KGD_Num>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const KGD_Num& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const KGD_Num& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KGD_Num* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "safeheron.proto.KGD_Num";
  }
  protected:
  explicit KGD_Num(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNumFieldNumber = 1,
    kBlindFactorFieldNumber = 2,
  };
  // string num = 1;
  void clear_num();
  const std::string& num() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_num(ArgT0&& arg0, ArgT... args);
  std::string* mutable_num();
  PROTOBUF_NODISCARD std::string* release_num();
  void set_allocated_num(std::string* num);
  private:
  const std::string& _internal_num() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_num(const std::string& value);
  std::string* _internal_mutable_num();
  public:

  // string blindFactor = 2;
  void clear_blindfactor();
  const std::string& blindfactor() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_blindfactor(ArgT0&& arg0, ArgT... args);
  std::string* mutable_blindfactor();
  PROTOBUF_NODISCARD std::string* release_blindfactor();
  void set_allocated_blindfactor(std::string* blindfactor);
  private:
  const std::string& _internal_blindfactor() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_blindfactor(const std::string& value);
  std::string* _internal_mutable_blindfactor();
  public:

  // @@protoc_insertion_point(class_scope:safeheron.proto.KGD_Num)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr num_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr blindfactor_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_commitment_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// KGD

// .safeheron.proto.CurvePoint y = 1;
inline bool KGD::_internal_has_y() const {
  return this != internal_default_instance() && y_ != nullptr;
}
inline bool KGD::has_y() const {
  return _internal_has_y();
}
inline const ::safeheron::proto::CurvePoint& KGD::_internal_y() const {
  const ::safeheron::proto::CurvePoint* p = y_;
  return p != nullptr ? *p : reinterpret_cast<const ::safeheron::proto::CurvePoint&>(
      ::safeheron::proto::_CurvePoint_default_instance_);
}
inline const ::safeheron::proto::CurvePoint& KGD::y() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.KGD.y)
  return _internal_y();
}
inline void KGD::unsafe_arena_set_allocated_y(
    ::safeheron::proto::CurvePoint* y) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(y_);
  }
  y_ = y;
  if (y) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:safeheron.proto.KGD.y)
}
inline ::safeheron::proto::CurvePoint* KGD::release_y() {
  
  ::safeheron::proto::CurvePoint* temp = y_;
  y_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::safeheron::proto::CurvePoint* KGD::unsafe_arena_release_y() {
  // @@protoc_insertion_point(field_release:safeheron.proto.KGD.y)
  
  ::safeheron::proto::CurvePoint* temp = y_;
  y_ = nullptr;
  return temp;
}
inline ::safeheron::proto::CurvePoint* KGD::_internal_mutable_y() {
  
  if (y_ == nullptr) {
    auto* p = CreateMaybeMessage<::safeheron::proto::CurvePoint>(GetArenaForAllocation());
    y_ = p;
  }
  return y_;
}
inline ::safeheron::proto::CurvePoint* KGD::mutable_y() {
  ::safeheron::proto::CurvePoint* _msg = _internal_mutable_y();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.KGD.y)
  return _msg;
}
inline void KGD::set_allocated_y(::safeheron::proto::CurvePoint* y) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(y_);
  }
  if (y) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(y));
    if (message_arena != submessage_arena) {
      y = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, y, submessage_arena);
    }
    
  } else {
    
  }
  y_ = y;
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.KGD.y)
}

// string blindFactor = 2;
inline void KGD::clear_blindfactor() {
  blindfactor_.ClearToEmpty();
}
inline const std::string& KGD::blindfactor() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.KGD.blindFactor)
  return _internal_blindfactor();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void KGD::set_blindfactor(ArgT0&& arg0, ArgT... args) {
 
 blindfactor_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.KGD.blindFactor)
}
inline std::string* KGD::mutable_blindfactor() {
  std::string* _s = _internal_mutable_blindfactor();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.KGD.blindFactor)
  return _s;
}
inline const std::string& KGD::_internal_blindfactor() const {
  return blindfactor_.Get();
}
inline void KGD::_internal_set_blindfactor(const std::string& value) {
  
  blindfactor_.Set(value, GetArenaForAllocation());
}
inline std::string* KGD::_internal_mutable_blindfactor() {
  
  return blindfactor_.Mutable(GetArenaForAllocation());
}
inline std::string* KGD::release_blindfactor() {
  // @@protoc_insertion_point(field_release:safeheron.proto.KGD.blindFactor)
  return blindfactor_.Release();
}
inline void KGD::set_allocated_blindfactor(std::string* blindfactor) {
  if (blindfactor != nullptr) {
    
  } else {
    
  }
  blindfactor_.SetAllocated(blindfactor, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (blindfactor_.IsDefault()) {
    blindfactor_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.KGD.blindFactor)
}

// -------------------------------------------------------------------

// KGD_Num

// string num = 1;
inline void KGD_Num::clear_num() {
  num_.ClearToEmpty();
}
inline const std::string& KGD_Num::num() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.KGD_Num.num)
  return _internal_num();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void KGD_Num::set_num(ArgT0&& arg0, ArgT... args) {
 
 num_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.KGD_Num.num)
}
inline std::string* KGD_Num::mutable_num() {
  std::string* _s = _internal_mutable_num();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.KGD_Num.num)
  return _s;
}
inline const std::string& KGD_Num::_internal_num() const {
  return num_.Get();
}
inline void KGD_Num::_internal_set_num(const std::string& value) {
  
  num_.Set(value, GetArenaForAllocation());
}
inline std::string* KGD_Num::_internal_mutable_num() {
  
  return num_.Mutable(GetArenaForAllocation());
}
inline std::string* KGD_Num::release_num() {
  // @@protoc_insertion_point(field_release:safeheron.proto.KGD_Num.num)
  return num_.Release();
}
inline void KGD_Num::set_allocated_num(std::string* num) {
  if (num != nullptr) {
    
  } else {
    
  }
  num_.SetAllocated(num, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (num_.IsDefault()) {
    num_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.KGD_Num.num)
}

// string blindFactor = 2;
inline void KGD_Num::clear_blindfactor() {
  blindfactor_.ClearToEmpty();
}
inline const std::string& KGD_Num::blindfactor() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.KGD_Num.blindFactor)
  return _internal_blindfactor();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void KGD_Num::set_blindfactor(ArgT0&& arg0, ArgT... args) {
 
 blindfactor_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.KGD_Num.blindFactor)
}
inline std::string* KGD_Num::mutable_blindfactor() {
  std::string* _s = _internal_mutable_blindfactor();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.KGD_Num.blindFactor)
  return _s;
}
inline const std::string& KGD_Num::_internal_blindfactor() const {
  return blindfactor_.Get();
}
inline void KGD_Num::_internal_set_blindfactor(const std::string& value) {
  
  blindfactor_.Set(value, GetArenaForAllocation());
}
inline std::string* KGD_Num::_internal_mutable_blindfactor() {
  
  return blindfactor_.Mutable(GetArenaForAllocation());
}
inline std::string* KGD_Num::release_blindfactor() {
  // @@protoc_insertion_point(field_release:safeheron.proto.KGD_Num.blindFactor)
  return blindfactor_.Release();
}
inline void KGD_Num::set_allocated_blindfactor(std::string* blindfactor) {
  if (blindfactor != nullptr) {
    
  } else {
    
  }
  blindfactor_.SetAllocated(blindfactor, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (blindfactor_.IsDefault()) {
    blindfactor_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.KGD_Num.blindFactor)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace safeheron

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_commitment_2eproto
