// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paillier.proto

#include "paillier.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace safeheron {
namespace proto {
class PailPubDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PailPub> _instance;
} _PailPub_default_instance_;
class PailPrivDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PailPriv> _instance;
} _PailPriv_default_instance_;
}  // namespace proto
}  // namespace safeheron
static void InitDefaultsscc_info_PailPriv_paillier_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::safeheron::proto::_PailPriv_default_instance_;
    new (ptr) ::safeheron::proto::PailPriv();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PailPriv_paillier_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_PailPriv_paillier_2eproto}, {}};

static void InitDefaultsscc_info_PailPub_paillier_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::safeheron::proto::_PailPub_default_instance_;
    new (ptr) ::safeheron::proto::PailPub();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PailPub_paillier_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_PailPub_paillier_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_paillier_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_paillier_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_paillier_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_paillier_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPub, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPub, n_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPub, g_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, n_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, lambda_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, mu_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, p_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, q_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, psqr_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, qsqr_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, pminus1_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, qminus1_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, hp_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, hq_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, qinvp_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, pinvq_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::safeheron::proto::PailPub)},
  { 7, -1, sizeof(::safeheron::proto::PailPriv)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::safeheron::proto::_PailPub_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::safeheron::proto::_PailPriv_default_instance_),
};

const char descriptor_table_protodef_paillier_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016paillier.proto\022\017safeheron.proto\"\037\n\007Pai"
  "lPub\022\t\n\001n\030\001 \001(\t\022\t\n\001g\030\002 \001(\t\"\273\001\n\010PailPriv\022"
  "\t\n\001n\030\001 \001(\t\022\016\n\006lambda\030\002 \001(\t\022\n\n\002mu\030\003 \001(\t\022\t"
  "\n\001p\030\004 \001(\t\022\t\n\001q\030\005 \001(\t\022\014\n\004pSqr\030\006 \001(\t\022\014\n\004qS"
  "qr\030\007 \001(\t\022\017\n\007pMinus1\030\010 \001(\t\022\017\n\007qMinus1\030\t \001"
  "(\t\022\n\n\002hp\030\n \001(\t\022\n\n\002hq\030\013 \001(\t\022\r\n\005qInvP\030\014 \001("
  "\t\022\r\n\005pInvQ\030\r \001(\tb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_paillier_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_paillier_2eproto_sccs[2] = {
  &scc_info_PailPriv_paillier_2eproto.base,
  &scc_info_PailPub_paillier_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_paillier_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_paillier_2eproto = {
  false, false, descriptor_table_protodef_paillier_2eproto, "paillier.proto", 264,
  &descriptor_table_paillier_2eproto_once, descriptor_table_paillier_2eproto_sccs, descriptor_table_paillier_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_paillier_2eproto::offsets,
  file_level_metadata_paillier_2eproto, 2, file_level_enum_descriptors_paillier_2eproto, file_level_service_descriptors_paillier_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_paillier_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_paillier_2eproto)), true);
namespace safeheron {
namespace proto {

// ===================================================================

class PailPub::_Internal {
 public:
};

PailPub::PailPub(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:safeheron.proto.PailPub)
}
PailPub::PailPub(const PailPub& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  n_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_n().empty()) {
    n_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_n(), 
      GetArena());
  }
  g_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_g().empty()) {
    g_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_g(), 
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:safeheron.proto.PailPub)
}

void PailPub::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PailPub_paillier_2eproto.base);
  n_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  g_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

PailPub::~PailPub() {
  // @@protoc_insertion_point(destructor:safeheron.proto.PailPub)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PailPub::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  n_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  g_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void PailPub::ArenaDtor(void* object) {
  PailPub* _this = reinterpret_cast< PailPub* >(object);
  (void)_this;
}
void PailPub::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PailPub::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PailPub& PailPub::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PailPub_paillier_2eproto.base);
  return *internal_default_instance();
}


void PailPub::Clear() {
// @@protoc_insertion_point(message_clear_start:safeheron.proto.PailPub)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  n_.ClearToEmpty();
  g_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PailPub::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string n = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_n();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.PailPub.n"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string g = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_g();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.PailPub.g"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PailPub::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:safeheron.proto.PailPub)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string n = 1;
  if (this->n().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_n().data(), static_cast<int>(this->_internal_n().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPub.n");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_n(), target);
  }

  // string g = 2;
  if (this->g().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_g().data(), static_cast<int>(this->_internal_g().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPub.g");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_g(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:safeheron.proto.PailPub)
  return target;
}

size_t PailPub::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:safeheron.proto.PailPub)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string n = 1;
  if (this->n().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_n());
  }

  // string g = 2;
  if (this->g().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_g());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PailPub::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:safeheron.proto.PailPub)
  GOOGLE_DCHECK_NE(&from, this);
  const PailPub* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PailPub>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:safeheron.proto.PailPub)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:safeheron.proto.PailPub)
    MergeFrom(*source);
  }
}

void PailPub::MergeFrom(const PailPub& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:safeheron.proto.PailPub)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.n().size() > 0) {
    _internal_set_n(from._internal_n());
  }
  if (from.g().size() > 0) {
    _internal_set_g(from._internal_g());
  }
}

void PailPub::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:safeheron.proto.PailPub)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PailPub::CopyFrom(const PailPub& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:safeheron.proto.PailPub)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PailPub::IsInitialized() const {
  return true;
}

void PailPub::InternalSwap(PailPub* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  n_.Swap(&other->n_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  g_.Swap(&other->g_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata PailPub::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class PailPriv::_Internal {
 public:
};

PailPriv::PailPriv(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:safeheron.proto.PailPriv)
}
PailPriv::PailPriv(const PailPriv& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  n_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_n().empty()) {
    n_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_n(), 
      GetArena());
  }
  lambda_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_lambda().empty()) {
    lambda_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_lambda(), 
      GetArena());
  }
  mu_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_mu().empty()) {
    mu_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_mu(), 
      GetArena());
  }
  p_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_p().empty()) {
    p_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_p(), 
      GetArena());
  }
  q_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_q().empty()) {
    q_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_q(), 
      GetArena());
  }
  psqr_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_psqr().empty()) {
    psqr_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_psqr(), 
      GetArena());
  }
  qsqr_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_qsqr().empty()) {
    qsqr_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_qsqr(), 
      GetArena());
  }
  pminus1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_pminus1().empty()) {
    pminus1_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_pminus1(), 
      GetArena());
  }
  qminus1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_qminus1().empty()) {
    qminus1_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_qminus1(), 
      GetArena());
  }
  hp_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_hp().empty()) {
    hp_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_hp(), 
      GetArena());
  }
  hq_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_hq().empty()) {
    hq_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_hq(), 
      GetArena());
  }
  qinvp_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_qinvp().empty()) {
    qinvp_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_qinvp(), 
      GetArena());
  }
  pinvq_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_pinvq().empty()) {
    pinvq_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_pinvq(), 
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:safeheron.proto.PailPriv)
}

void PailPriv::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PailPriv_paillier_2eproto.base);
  n_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  lambda_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  mu_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  p_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  q_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  psqr_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  qsqr_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  pminus1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  qminus1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  hp_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  hq_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  qinvp_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  pinvq_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

PailPriv::~PailPriv() {
  // @@protoc_insertion_point(destructor:safeheron.proto.PailPriv)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PailPriv::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  n_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  lambda_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  mu_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  p_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  q_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  psqr_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  qsqr_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  pminus1_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  qminus1_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  hp_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  hq_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  qinvp_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  pinvq_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void PailPriv::ArenaDtor(void* object) {
  PailPriv* _this = reinterpret_cast< PailPriv* >(object);
  (void)_this;
}
void PailPriv::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PailPriv::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PailPriv& PailPriv::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PailPriv_paillier_2eproto.base);
  return *internal_default_instance();
}


void PailPriv::Clear() {
// @@protoc_insertion_point(message_clear_start:safeheron.proto.PailPriv)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  n_.ClearToEmpty();
  lambda_.ClearToEmpty();
  mu_.ClearToEmpty();
  p_.ClearToEmpty();
  q_.ClearToEmpty();
  psqr_.ClearToEmpty();
  qsqr_.ClearToEmpty();
  pminus1_.ClearToEmpty();
  qminus1_.ClearToEmpty();
  hp_.ClearToEmpty();
  hq_.ClearToEmpty();
  qinvp_.ClearToEmpty();
  pinvq_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PailPriv::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string n = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_n();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.PailPriv.n"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string lambda = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_lambda();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.PailPriv.lambda"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string mu = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_mu();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.PailPriv.mu"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string p = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_p();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.PailPriv.p"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string q = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          auto str = _internal_mutable_q();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.PailPriv.q"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string pSqr = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          auto str = _internal_mutable_psqr();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.PailPriv.pSqr"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string qSqr = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          auto str = _internal_mutable_qsqr();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.PailPriv.qSqr"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string pMinus1 = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          auto str = _internal_mutable_pminus1();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.PailPriv.pMinus1"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string qMinus1 = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          auto str = _internal_mutable_qminus1();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.PailPriv.qMinus1"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string hp = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82)) {
          auto str = _internal_mutable_hp();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.PailPriv.hp"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string hq = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 90)) {
          auto str = _internal_mutable_hq();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.PailPriv.hq"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string qInvP = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 98)) {
          auto str = _internal_mutable_qinvp();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.PailPriv.qInvP"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string pInvQ = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 106)) {
          auto str = _internal_mutable_pinvq();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "safeheron.proto.PailPriv.pInvQ"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PailPriv::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:safeheron.proto.PailPriv)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string n = 1;
  if (this->n().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_n().data(), static_cast<int>(this->_internal_n().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.n");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_n(), target);
  }

  // string lambda = 2;
  if (this->lambda().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_lambda().data(), static_cast<int>(this->_internal_lambda().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.lambda");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_lambda(), target);
  }

  // string mu = 3;
  if (this->mu().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_mu().data(), static_cast<int>(this->_internal_mu().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.mu");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_mu(), target);
  }

  // string p = 4;
  if (this->p().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_p().data(), static_cast<int>(this->_internal_p().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.p");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_p(), target);
  }

  // string q = 5;
  if (this->q().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_q().data(), static_cast<int>(this->_internal_q().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.q");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_q(), target);
  }

  // string pSqr = 6;
  if (this->psqr().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_psqr().data(), static_cast<int>(this->_internal_psqr().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.pSqr");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_psqr(), target);
  }

  // string qSqr = 7;
  if (this->qsqr().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_qsqr().data(), static_cast<int>(this->_internal_qsqr().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.qSqr");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_qsqr(), target);
  }

  // string pMinus1 = 8;
  if (this->pminus1().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_pminus1().data(), static_cast<int>(this->_internal_pminus1().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.pMinus1");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_pminus1(), target);
  }

  // string qMinus1 = 9;
  if (this->qminus1().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_qminus1().data(), static_cast<int>(this->_internal_qminus1().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.qMinus1");
    target = stream->WriteStringMaybeAliased(
        9, this->_internal_qminus1(), target);
  }

  // string hp = 10;
  if (this->hp().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_hp().data(), static_cast<int>(this->_internal_hp().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.hp");
    target = stream->WriteStringMaybeAliased(
        10, this->_internal_hp(), target);
  }

  // string hq = 11;
  if (this->hq().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_hq().data(), static_cast<int>(this->_internal_hq().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.hq");
    target = stream->WriteStringMaybeAliased(
        11, this->_internal_hq(), target);
  }

  // string qInvP = 12;
  if (this->qinvp().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_qinvp().data(), static_cast<int>(this->_internal_qinvp().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.qInvP");
    target = stream->WriteStringMaybeAliased(
        12, this->_internal_qinvp(), target);
  }

  // string pInvQ = 13;
  if (this->pinvq().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_pinvq().data(), static_cast<int>(this->_internal_pinvq().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.pInvQ");
    target = stream->WriteStringMaybeAliased(
        13, this->_internal_pinvq(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:safeheron.proto.PailPriv)
  return target;
}

size_t PailPriv::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:safeheron.proto.PailPriv)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string n = 1;
  if (this->n().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_n());
  }

  // string lambda = 2;
  if (this->lambda().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_lambda());
  }

  // string mu = 3;
  if (this->mu().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_mu());
  }

  // string p = 4;
  if (this->p().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_p());
  }

  // string q = 5;
  if (this->q().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_q());
  }

  // string pSqr = 6;
  if (this->psqr().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_psqr());
  }

  // string qSqr = 7;
  if (this->qsqr().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_qsqr());
  }

  // string pMinus1 = 8;
  if (this->pminus1().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_pminus1());
  }

  // string qMinus1 = 9;
  if (this->qminus1().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_qminus1());
  }

  // string hp = 10;
  if (this->hp().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_hp());
  }

  // string hq = 11;
  if (this->hq().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_hq());
  }

  // string qInvP = 12;
  if (this->qinvp().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_qinvp());
  }

  // string pInvQ = 13;
  if (this->pinvq().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_pinvq());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PailPriv::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:safeheron.proto.PailPriv)
  GOOGLE_DCHECK_NE(&from, this);
  const PailPriv* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PailPriv>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:safeheron.proto.PailPriv)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:safeheron.proto.PailPriv)
    MergeFrom(*source);
  }
}

void PailPriv::MergeFrom(const PailPriv& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:safeheron.proto.PailPriv)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.n().size() > 0) {
    _internal_set_n(from._internal_n());
  }
  if (from.lambda().size() > 0) {
    _internal_set_lambda(from._internal_lambda());
  }
  if (from.mu().size() > 0) {
    _internal_set_mu(from._internal_mu());
  }
  if (from.p().size() > 0) {
    _internal_set_p(from._internal_p());
  }
  if (from.q().size() > 0) {
    _internal_set_q(from._internal_q());
  }
  if (from.psqr().size() > 0) {
    _internal_set_psqr(from._internal_psqr());
  }
  if (from.qsqr().size() > 0) {
    _internal_set_qsqr(from._internal_qsqr());
  }
  if (from.pminus1().size() > 0) {
    _internal_set_pminus1(from._internal_pminus1());
  }
  if (from.qminus1().size() > 0) {
    _internal_set_qminus1(from._internal_qminus1());
  }
  if (from.hp().size() > 0) {
    _internal_set_hp(from._internal_hp());
  }
  if (from.hq().size() > 0) {
    _internal_set_hq(from._internal_hq());
  }
  if (from.qinvp().size() > 0) {
    _internal_set_qinvp(from._internal_qinvp());
  }
  if (from.pinvq().size() > 0) {
    _internal_set_pinvq(from._internal_pinvq());
  }
}

void PailPriv::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:safeheron.proto.PailPriv)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PailPriv::CopyFrom(const PailPriv& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:safeheron.proto.PailPriv)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PailPriv::IsInitialized() const {
  return true;
}

void PailPriv::InternalSwap(PailPriv* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  n_.Swap(&other->n_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  lambda_.Swap(&other->lambda_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  mu_.Swap(&other->mu_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  p_.Swap(&other->p_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  q_.Swap(&other->q_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  psqr_.Swap(&other->psqr_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  qsqr_.Swap(&other->qsqr_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  pminus1_.Swap(&other->pminus1_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  qminus1_.Swap(&other->qminus1_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  hp_.Swap(&other->hp_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  hq_.Swap(&other->hq_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  qinvp_.Swap(&other->qinvp_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  pinvq_.Swap(&other->pinvq_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata PailPriv::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace safeheron
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::safeheron::proto::PailPub* Arena::CreateMaybeMessage< ::safeheron::proto::PailPub >(Arena* arena) {
  return Arena::CreateMessageInternal< ::safeheron::proto::PailPub >(arena);
}
template<> PROTOBUF_NOINLINE ::safeheron::proto::PailPriv* Arena::CreateMaybeMessage< ::safeheron::proto::PailPriv >(Arena* arena) {
  return Arena::CreateMessageInternal< ::safeheron::proto::PailPriv >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
