// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commitment.proto

#include "commitment.pb.switch.h"

#include <google/protobuf/port_def.inc>

#if PROTOBUF_VERSION >= 3014000 && 3014000 >= PROTOBUF_MIN_PROTOC_VERSION
#include <google/protobuf/port_undef.inc>
#include "3_14/commitment.pb.cc"
#elif PROTOBUF_VERSION >= 3020000 && 3020000 >= PROTOBUF_MIN_PROTOC_VERSION
#include <google/protobuf/port_undef.inc>
#include "3_20/commitment.pb.cc"
#else
#error Invalid version of protobuf.
#endif
