// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paillier.proto

#include "paillier.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace safeheron {
namespace proto {
PROTOBUF_CONSTEXPR PailPub::PailPub(
    ::_pbi::ConstantInitialized)
  : n_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , g_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}){}
struct PailPubDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PailPubDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PailPubDefaultTypeInternal() {}
  union {
    PailPub _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PailPubDefaultTypeInternal _PailPub_default_instance_;
PROTOBUF_CONSTEXPR PailPriv::PailPriv(
    ::_pbi::ConstantInitialized)
  : n_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , lambda_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , mu_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , p_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , q_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , psqr_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , qsqr_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , pminus1_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , qminus1_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , hp_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , hq_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , qinvp_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , pinvq_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}){}
struct PailPrivDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PailPrivDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PailPrivDefaultTypeInternal() {}
  union {
    PailPriv _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PailPrivDefaultTypeInternal _PailPriv_default_instance_;
}  // namespace proto
}  // namespace safeheron
static ::_pb::Metadata file_level_metadata_paillier_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_paillier_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_paillier_2eproto = nullptr;

const uint32_t TableStruct_paillier_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPub, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPub, n_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPub, g_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, n_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, lambda_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, mu_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, p_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, q_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, psqr_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, qsqr_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, pminus1_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, qminus1_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, hp_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, hq_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, qinvp_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::PailPriv, pinvq_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::safeheron::proto::PailPub)},
  { 8, -1, -1, sizeof(::safeheron::proto::PailPriv)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::safeheron::proto::_PailPub_default_instance_._instance,
  &::safeheron::proto::_PailPriv_default_instance_._instance,
};

const char descriptor_table_protodef_paillier_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016paillier.proto\022\017safeheron.proto\"\037\n\007Pai"
  "lPub\022\t\n\001n\030\001 \001(\t\022\t\n\001g\030\002 \001(\t\"\273\001\n\010PailPriv\022"
  "\t\n\001n\030\001 \001(\t\022\016\n\006lambda\030\002 \001(\t\022\n\n\002mu\030\003 \001(\t\022\t"
  "\n\001p\030\004 \001(\t\022\t\n\001q\030\005 \001(\t\022\014\n\004pSqr\030\006 \001(\t\022\014\n\004qS"
  "qr\030\007 \001(\t\022\017\n\007pMinus1\030\010 \001(\t\022\017\n\007qMinus1\030\t \001"
  "(\t\022\n\n\002hp\030\n \001(\t\022\n\n\002hq\030\013 \001(\t\022\r\n\005qInvP\030\014 \001("
  "\t\022\r\n\005pInvQ\030\r \001(\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_paillier_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_paillier_2eproto = {
    false, false, 264, descriptor_table_protodef_paillier_2eproto,
    "paillier.proto",
    &descriptor_table_paillier_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_paillier_2eproto::offsets,
    file_level_metadata_paillier_2eproto, file_level_enum_descriptors_paillier_2eproto,
    file_level_service_descriptors_paillier_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_paillier_2eproto_getter() {
  return &descriptor_table_paillier_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_paillier_2eproto(&descriptor_table_paillier_2eproto);
namespace safeheron {
namespace proto {

// ===================================================================

class PailPub::_Internal {
 public:
};

PailPub::PailPub(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:safeheron.proto.PailPub)
}
PailPub::PailPub(const PailPub& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  n_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    n_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_n().empty()) {
    n_.Set(from._internal_n(), 
      GetArenaForAllocation());
  }
  g_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    g_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_g().empty()) {
    g_.Set(from._internal_g(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:safeheron.proto.PailPub)
}

inline void PailPub::SharedCtor() {
n_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  n_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
g_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  g_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PailPub::~PailPub() {
  // @@protoc_insertion_point(destructor:safeheron.proto.PailPub)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PailPub::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  n_.Destroy();
  g_.Destroy();
}

void PailPub::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void PailPub::Clear() {
// @@protoc_insertion_point(message_clear_start:safeheron.proto.PailPub)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  n_.ClearToEmpty();
  g_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PailPub::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string n = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_n();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "safeheron.proto.PailPub.n"));
        } else
          goto handle_unusual;
        continue;
      // string g = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_g();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "safeheron.proto.PailPub.g"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PailPub::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:safeheron.proto.PailPub)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string n = 1;
  if (!this->_internal_n().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_n().data(), static_cast<int>(this->_internal_n().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPub.n");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_n(), target);
  }

  // string g = 2;
  if (!this->_internal_g().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_g().data(), static_cast<int>(this->_internal_g().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPub.g");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_g(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:safeheron.proto.PailPub)
  return target;
}

size_t PailPub::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:safeheron.proto.PailPub)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string n = 1;
  if (!this->_internal_n().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_n());
  }

  // string g = 2;
  if (!this->_internal_g().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_g());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PailPub::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    PailPub::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PailPub::GetClassData() const { return &_class_data_; }

void PailPub::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<PailPub *>(to)->MergeFrom(
      static_cast<const PailPub &>(from));
}


void PailPub::MergeFrom(const PailPub& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:safeheron.proto.PailPub)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_n().empty()) {
    _internal_set_n(from._internal_n());
  }
  if (!from._internal_g().empty()) {
    _internal_set_g(from._internal_g());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PailPub::CopyFrom(const PailPub& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:safeheron.proto.PailPub)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PailPub::IsInitialized() const {
  return true;
}

void PailPub::InternalSwap(PailPub* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &n_, lhs_arena,
      &other->n_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &g_, lhs_arena,
      &other->g_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata PailPub::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_paillier_2eproto_getter, &descriptor_table_paillier_2eproto_once,
      file_level_metadata_paillier_2eproto[0]);
}

// ===================================================================

class PailPriv::_Internal {
 public:
};

PailPriv::PailPriv(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:safeheron.proto.PailPriv)
}
PailPriv::PailPriv(const PailPriv& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  n_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    n_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_n().empty()) {
    n_.Set(from._internal_n(), 
      GetArenaForAllocation());
  }
  lambda_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    lambda_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_lambda().empty()) {
    lambda_.Set(from._internal_lambda(), 
      GetArenaForAllocation());
  }
  mu_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    mu_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_mu().empty()) {
    mu_.Set(from._internal_mu(), 
      GetArenaForAllocation());
  }
  p_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    p_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_p().empty()) {
    p_.Set(from._internal_p(), 
      GetArenaForAllocation());
  }
  q_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    q_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_q().empty()) {
    q_.Set(from._internal_q(), 
      GetArenaForAllocation());
  }
  psqr_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    psqr_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_psqr().empty()) {
    psqr_.Set(from._internal_psqr(), 
      GetArenaForAllocation());
  }
  qsqr_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    qsqr_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_qsqr().empty()) {
    qsqr_.Set(from._internal_qsqr(), 
      GetArenaForAllocation());
  }
  pminus1_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    pminus1_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_pminus1().empty()) {
    pminus1_.Set(from._internal_pminus1(), 
      GetArenaForAllocation());
  }
  qminus1_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    qminus1_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_qminus1().empty()) {
    qminus1_.Set(from._internal_qminus1(), 
      GetArenaForAllocation());
  }
  hp_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    hp_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_hp().empty()) {
    hp_.Set(from._internal_hp(), 
      GetArenaForAllocation());
  }
  hq_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    hq_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_hq().empty()) {
    hq_.Set(from._internal_hq(), 
      GetArenaForAllocation());
  }
  qinvp_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    qinvp_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_qinvp().empty()) {
    qinvp_.Set(from._internal_qinvp(), 
      GetArenaForAllocation());
  }
  pinvq_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    pinvq_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_pinvq().empty()) {
    pinvq_.Set(from._internal_pinvq(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:safeheron.proto.PailPriv)
}

inline void PailPriv::SharedCtor() {
n_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  n_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
lambda_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  lambda_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
mu_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  mu_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
p_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  p_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
q_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  q_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
psqr_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  psqr_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
qsqr_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  qsqr_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
pminus1_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  pminus1_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
qminus1_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  qminus1_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
hp_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  hp_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
hq_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  hq_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
qinvp_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  qinvp_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
pinvq_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  pinvq_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PailPriv::~PailPriv() {
  // @@protoc_insertion_point(destructor:safeheron.proto.PailPriv)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PailPriv::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  n_.Destroy();
  lambda_.Destroy();
  mu_.Destroy();
  p_.Destroy();
  q_.Destroy();
  psqr_.Destroy();
  qsqr_.Destroy();
  pminus1_.Destroy();
  qminus1_.Destroy();
  hp_.Destroy();
  hq_.Destroy();
  qinvp_.Destroy();
  pinvq_.Destroy();
}

void PailPriv::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void PailPriv::Clear() {
// @@protoc_insertion_point(message_clear_start:safeheron.proto.PailPriv)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  n_.ClearToEmpty();
  lambda_.ClearToEmpty();
  mu_.ClearToEmpty();
  p_.ClearToEmpty();
  q_.ClearToEmpty();
  psqr_.ClearToEmpty();
  qsqr_.ClearToEmpty();
  pminus1_.ClearToEmpty();
  qminus1_.ClearToEmpty();
  hp_.ClearToEmpty();
  hq_.ClearToEmpty();
  qinvp_.ClearToEmpty();
  pinvq_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PailPriv::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string n = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_n();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "safeheron.proto.PailPriv.n"));
        } else
          goto handle_unusual;
        continue;
      // string lambda = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_lambda();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "safeheron.proto.PailPriv.lambda"));
        } else
          goto handle_unusual;
        continue;
      // string mu = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_mu();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "safeheron.proto.PailPriv.mu"));
        } else
          goto handle_unusual;
        continue;
      // string p = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_p();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "safeheron.proto.PailPriv.p"));
        } else
          goto handle_unusual;
        continue;
      // string q = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_q();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "safeheron.proto.PailPriv.q"));
        } else
          goto handle_unusual;
        continue;
      // string pSqr = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_psqr();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "safeheron.proto.PailPriv.pSqr"));
        } else
          goto handle_unusual;
        continue;
      // string qSqr = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_qsqr();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "safeheron.proto.PailPriv.qSqr"));
        } else
          goto handle_unusual;
        continue;
      // string pMinus1 = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_pminus1();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "safeheron.proto.PailPriv.pMinus1"));
        } else
          goto handle_unusual;
        continue;
      // string qMinus1 = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          auto str = _internal_mutable_qminus1();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "safeheron.proto.PailPriv.qMinus1"));
        } else
          goto handle_unusual;
        continue;
      // string hp = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          auto str = _internal_mutable_hp();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "safeheron.proto.PailPriv.hp"));
        } else
          goto handle_unusual;
        continue;
      // string hq = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          auto str = _internal_mutable_hq();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "safeheron.proto.PailPriv.hq"));
        } else
          goto handle_unusual;
        continue;
      // string qInvP = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 98)) {
          auto str = _internal_mutable_qinvp();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "safeheron.proto.PailPriv.qInvP"));
        } else
          goto handle_unusual;
        continue;
      // string pInvQ = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 106)) {
          auto str = _internal_mutable_pinvq();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "safeheron.proto.PailPriv.pInvQ"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PailPriv::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:safeheron.proto.PailPriv)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string n = 1;
  if (!this->_internal_n().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_n().data(), static_cast<int>(this->_internal_n().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.n");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_n(), target);
  }

  // string lambda = 2;
  if (!this->_internal_lambda().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_lambda().data(), static_cast<int>(this->_internal_lambda().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.lambda");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_lambda(), target);
  }

  // string mu = 3;
  if (!this->_internal_mu().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_mu().data(), static_cast<int>(this->_internal_mu().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.mu");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_mu(), target);
  }

  // string p = 4;
  if (!this->_internal_p().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_p().data(), static_cast<int>(this->_internal_p().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.p");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_p(), target);
  }

  // string q = 5;
  if (!this->_internal_q().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_q().data(), static_cast<int>(this->_internal_q().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.q");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_q(), target);
  }

  // string pSqr = 6;
  if (!this->_internal_psqr().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_psqr().data(), static_cast<int>(this->_internal_psqr().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.pSqr");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_psqr(), target);
  }

  // string qSqr = 7;
  if (!this->_internal_qsqr().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_qsqr().data(), static_cast<int>(this->_internal_qsqr().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.qSqr");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_qsqr(), target);
  }

  // string pMinus1 = 8;
  if (!this->_internal_pminus1().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_pminus1().data(), static_cast<int>(this->_internal_pminus1().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.pMinus1");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_pminus1(), target);
  }

  // string qMinus1 = 9;
  if (!this->_internal_qminus1().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_qminus1().data(), static_cast<int>(this->_internal_qminus1().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.qMinus1");
    target = stream->WriteStringMaybeAliased(
        9, this->_internal_qminus1(), target);
  }

  // string hp = 10;
  if (!this->_internal_hp().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_hp().data(), static_cast<int>(this->_internal_hp().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.hp");
    target = stream->WriteStringMaybeAliased(
        10, this->_internal_hp(), target);
  }

  // string hq = 11;
  if (!this->_internal_hq().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_hq().data(), static_cast<int>(this->_internal_hq().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.hq");
    target = stream->WriteStringMaybeAliased(
        11, this->_internal_hq(), target);
  }

  // string qInvP = 12;
  if (!this->_internal_qinvp().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_qinvp().data(), static_cast<int>(this->_internal_qinvp().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.qInvP");
    target = stream->WriteStringMaybeAliased(
        12, this->_internal_qinvp(), target);
  }

  // string pInvQ = 13;
  if (!this->_internal_pinvq().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_pinvq().data(), static_cast<int>(this->_internal_pinvq().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.PailPriv.pInvQ");
    target = stream->WriteStringMaybeAliased(
        13, this->_internal_pinvq(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:safeheron.proto.PailPriv)
  return target;
}

size_t PailPriv::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:safeheron.proto.PailPriv)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string n = 1;
  if (!this->_internal_n().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_n());
  }

  // string lambda = 2;
  if (!this->_internal_lambda().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_lambda());
  }

  // string mu = 3;
  if (!this->_internal_mu().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_mu());
  }

  // string p = 4;
  if (!this->_internal_p().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_p());
  }

  // string q = 5;
  if (!this->_internal_q().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_q());
  }

  // string pSqr = 6;
  if (!this->_internal_psqr().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_psqr());
  }

  // string qSqr = 7;
  if (!this->_internal_qsqr().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_qsqr());
  }

  // string pMinus1 = 8;
  if (!this->_internal_pminus1().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_pminus1());
  }

  // string qMinus1 = 9;
  if (!this->_internal_qminus1().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_qminus1());
  }

  // string hp = 10;
  if (!this->_internal_hp().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_hp());
  }

  // string hq = 11;
  if (!this->_internal_hq().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_hq());
  }

  // string qInvP = 12;
  if (!this->_internal_qinvp().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_qinvp());
  }

  // string pInvQ = 13;
  if (!this->_internal_pinvq().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_pinvq());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PailPriv::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    PailPriv::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PailPriv::GetClassData() const { return &_class_data_; }

void PailPriv::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<PailPriv *>(to)->MergeFrom(
      static_cast<const PailPriv &>(from));
}


void PailPriv::MergeFrom(const PailPriv& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:safeheron.proto.PailPriv)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_n().empty()) {
    _internal_set_n(from._internal_n());
  }
  if (!from._internal_lambda().empty()) {
    _internal_set_lambda(from._internal_lambda());
  }
  if (!from._internal_mu().empty()) {
    _internal_set_mu(from._internal_mu());
  }
  if (!from._internal_p().empty()) {
    _internal_set_p(from._internal_p());
  }
  if (!from._internal_q().empty()) {
    _internal_set_q(from._internal_q());
  }
  if (!from._internal_psqr().empty()) {
    _internal_set_psqr(from._internal_psqr());
  }
  if (!from._internal_qsqr().empty()) {
    _internal_set_qsqr(from._internal_qsqr());
  }
  if (!from._internal_pminus1().empty()) {
    _internal_set_pminus1(from._internal_pminus1());
  }
  if (!from._internal_qminus1().empty()) {
    _internal_set_qminus1(from._internal_qminus1());
  }
  if (!from._internal_hp().empty()) {
    _internal_set_hp(from._internal_hp());
  }
  if (!from._internal_hq().empty()) {
    _internal_set_hq(from._internal_hq());
  }
  if (!from._internal_qinvp().empty()) {
    _internal_set_qinvp(from._internal_qinvp());
  }
  if (!from._internal_pinvq().empty()) {
    _internal_set_pinvq(from._internal_pinvq());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PailPriv::CopyFrom(const PailPriv& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:safeheron.proto.PailPriv)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PailPriv::IsInitialized() const {
  return true;
}

void PailPriv::InternalSwap(PailPriv* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &n_, lhs_arena,
      &other->n_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &lambda_, lhs_arena,
      &other->lambda_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &mu_, lhs_arena,
      &other->mu_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &p_, lhs_arena,
      &other->p_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &q_, lhs_arena,
      &other->q_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &psqr_, lhs_arena,
      &other->psqr_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &qsqr_, lhs_arena,
      &other->qsqr_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &pminus1_, lhs_arena,
      &other->pminus1_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &qminus1_, lhs_arena,
      &other->qminus1_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &hp_, lhs_arena,
      &other->hp_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &hq_, lhs_arena,
      &other->hq_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &qinvp_, lhs_arena,
      &other->qinvp_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &pinvq_, lhs_arena,
      &other->pinvq_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata PailPriv::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_paillier_2eproto_getter, &descriptor_table_paillier_2eproto_once,
      file_level_metadata_paillier_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace safeheron
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::safeheron::proto::PailPub*
Arena::CreateMaybeMessage< ::safeheron::proto::PailPub >(Arena* arena) {
  return Arena::CreateMessageInternal< ::safeheron::proto::PailPub >(arena);
}
template<> PROTOBUF_NOINLINE ::safeheron::proto::PailPriv*
Arena::CreateMaybeMessage< ::safeheron::proto::PailPriv >(Arena* arena) {
  return Arena::CreateMessageInternal< ::safeheron::proto::PailPriv >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
