// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paillier.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_paillier_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_paillier_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_paillier_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_paillier_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_paillier_2eproto;
namespace safeheron {
namespace proto {
class PailPriv;
struct PailPrivDefaultTypeInternal;
extern PailPrivDefaultTypeInternal _PailPriv_default_instance_;
class PailPub;
struct PailPubDefaultTypeInternal;
extern PailPubDefaultTypeInternal _PailPub_default_instance_;
}  // namespace proto
}  // namespace safeheron
PROTOBUF_NAMESPACE_OPEN
template<> ::safeheron::proto::PailPriv* Arena::CreateMaybeMessage<::safeheron::proto::PailPriv>(Arena*);
template<> ::safeheron::proto::PailPub* Arena::CreateMaybeMessage<::safeheron::proto::PailPub>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace safeheron {
namespace proto {

// ===================================================================

class PailPub final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.PailPub) */ {
 public:
  inline PailPub() : PailPub(nullptr) {}
  ~PailPub() override;
  explicit PROTOBUF_CONSTEXPR PailPub(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PailPub(const PailPub& from);
  PailPub(PailPub&& from) noexcept
    : PailPub() {
    *this = ::std::move(from);
  }

  inline PailPub& operator=(const PailPub& from) {
    CopyFrom(from);
    return *this;
  }
  inline PailPub& operator=(PailPub&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PailPub& default_instance() {
    return *internal_default_instance();
  }
  static inline const PailPub* internal_default_instance() {
    return reinterpret_cast<const PailPub*>(
               &_PailPub_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PailPub& a, PailPub& b) {
    a.Swap(&b);
  }
  inline void Swap(PailPub* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PailPub* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PailPub* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PailPub>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PailPub& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const PailPub& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PailPub* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "safeheron.proto.PailPub";
  }
  protected:
  explicit PailPub(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNFieldNumber = 1,
    kGFieldNumber = 2,
  };
  // string n = 1;
  void clear_n();
  const std::string& n() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_n(ArgT0&& arg0, ArgT... args);
  std::string* mutable_n();
  PROTOBUF_NODISCARD std::string* release_n();
  void set_allocated_n(std::string* n);
  private:
  const std::string& _internal_n() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_n(const std::string& value);
  std::string* _internal_mutable_n();
  public:

  // string g = 2;
  void clear_g();
  const std::string& g() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_g(ArgT0&& arg0, ArgT... args);
  std::string* mutable_g();
  PROTOBUF_NODISCARD std::string* release_g();
  void set_allocated_g(std::string* g);
  private:
  const std::string& _internal_g() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_g(const std::string& value);
  std::string* _internal_mutable_g();
  public:

  // @@protoc_insertion_point(class_scope:safeheron.proto.PailPub)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr n_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr g_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_paillier_2eproto;
};
// -------------------------------------------------------------------

class PailPriv final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.PailPriv) */ {
 public:
  inline PailPriv() : PailPriv(nullptr) {}
  ~PailPriv() override;
  explicit PROTOBUF_CONSTEXPR PailPriv(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PailPriv(const PailPriv& from);
  PailPriv(PailPriv&& from) noexcept
    : PailPriv() {
    *this = ::std::move(from);
  }

  inline PailPriv& operator=(const PailPriv& from) {
    CopyFrom(from);
    return *this;
  }
  inline PailPriv& operator=(PailPriv&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PailPriv& default_instance() {
    return *internal_default_instance();
  }
  static inline const PailPriv* internal_default_instance() {
    return reinterpret_cast<const PailPriv*>(
               &_PailPriv_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PailPriv& a, PailPriv& b) {
    a.Swap(&b);
  }
  inline void Swap(PailPriv* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PailPriv* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PailPriv* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PailPriv>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PailPriv& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const PailPriv& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PailPriv* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "safeheron.proto.PailPriv";
  }
  protected:
  explicit PailPriv(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNFieldNumber = 1,
    kLambdaFieldNumber = 2,
    kMuFieldNumber = 3,
    kPFieldNumber = 4,
    kQFieldNumber = 5,
    kPSqrFieldNumber = 6,
    kQSqrFieldNumber = 7,
    kPMinus1FieldNumber = 8,
    kQMinus1FieldNumber = 9,
    kHpFieldNumber = 10,
    kHqFieldNumber = 11,
    kQInvPFieldNumber = 12,
    kPInvQFieldNumber = 13,
  };
  // string n = 1;
  void clear_n();
  const std::string& n() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_n(ArgT0&& arg0, ArgT... args);
  std::string* mutable_n();
  PROTOBUF_NODISCARD std::string* release_n();
  void set_allocated_n(std::string* n);
  private:
  const std::string& _internal_n() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_n(const std::string& value);
  std::string* _internal_mutable_n();
  public:

  // string lambda = 2;
  void clear_lambda();
  const std::string& lambda() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_lambda(ArgT0&& arg0, ArgT... args);
  std::string* mutable_lambda();
  PROTOBUF_NODISCARD std::string* release_lambda();
  void set_allocated_lambda(std::string* lambda);
  private:
  const std::string& _internal_lambda() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_lambda(const std::string& value);
  std::string* _internal_mutable_lambda();
  public:

  // string mu = 3;
  void clear_mu();
  const std::string& mu() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_mu(ArgT0&& arg0, ArgT... args);
  std::string* mutable_mu();
  PROTOBUF_NODISCARD std::string* release_mu();
  void set_allocated_mu(std::string* mu);
  private:
  const std::string& _internal_mu() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_mu(const std::string& value);
  std::string* _internal_mutable_mu();
  public:

  // string p = 4;
  void clear_p();
  const std::string& p() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_p(ArgT0&& arg0, ArgT... args);
  std::string* mutable_p();
  PROTOBUF_NODISCARD std::string* release_p();
  void set_allocated_p(std::string* p);
  private:
  const std::string& _internal_p() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_p(const std::string& value);
  std::string* _internal_mutable_p();
  public:

  // string q = 5;
  void clear_q();
  const std::string& q() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_q(ArgT0&& arg0, ArgT... args);
  std::string* mutable_q();
  PROTOBUF_NODISCARD std::string* release_q();
  void set_allocated_q(std::string* q);
  private:
  const std::string& _internal_q() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_q(const std::string& value);
  std::string* _internal_mutable_q();
  public:

  // string pSqr = 6;
  void clear_psqr();
  const std::string& psqr() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_psqr(ArgT0&& arg0, ArgT... args);
  std::string* mutable_psqr();
  PROTOBUF_NODISCARD std::string* release_psqr();
  void set_allocated_psqr(std::string* psqr);
  private:
  const std::string& _internal_psqr() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_psqr(const std::string& value);
  std::string* _internal_mutable_psqr();
  public:

  // string qSqr = 7;
  void clear_qsqr();
  const std::string& qsqr() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_qsqr(ArgT0&& arg0, ArgT... args);
  std::string* mutable_qsqr();
  PROTOBUF_NODISCARD std::string* release_qsqr();
  void set_allocated_qsqr(std::string* qsqr);
  private:
  const std::string& _internal_qsqr() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_qsqr(const std::string& value);
  std::string* _internal_mutable_qsqr();
  public:

  // string pMinus1 = 8;
  void clear_pminus1();
  const std::string& pminus1() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_pminus1(ArgT0&& arg0, ArgT... args);
  std::string* mutable_pminus1();
  PROTOBUF_NODISCARD std::string* release_pminus1();
  void set_allocated_pminus1(std::string* pminus1);
  private:
  const std::string& _internal_pminus1() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pminus1(const std::string& value);
  std::string* _internal_mutable_pminus1();
  public:

  // string qMinus1 = 9;
  void clear_qminus1();
  const std::string& qminus1() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_qminus1(ArgT0&& arg0, ArgT... args);
  std::string* mutable_qminus1();
  PROTOBUF_NODISCARD std::string* release_qminus1();
  void set_allocated_qminus1(std::string* qminus1);
  private:
  const std::string& _internal_qminus1() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_qminus1(const std::string& value);
  std::string* _internal_mutable_qminus1();
  public:

  // string hp = 10;
  void clear_hp();
  const std::string& hp() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_hp(ArgT0&& arg0, ArgT... args);
  std::string* mutable_hp();
  PROTOBUF_NODISCARD std::string* release_hp();
  void set_allocated_hp(std::string* hp);
  private:
  const std::string& _internal_hp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_hp(const std::string& value);
  std::string* _internal_mutable_hp();
  public:

  // string hq = 11;
  void clear_hq();
  const std::string& hq() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_hq(ArgT0&& arg0, ArgT... args);
  std::string* mutable_hq();
  PROTOBUF_NODISCARD std::string* release_hq();
  void set_allocated_hq(std::string* hq);
  private:
  const std::string& _internal_hq() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_hq(const std::string& value);
  std::string* _internal_mutable_hq();
  public:

  // string qInvP = 12;
  void clear_qinvp();
  const std::string& qinvp() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_qinvp(ArgT0&& arg0, ArgT... args);
  std::string* mutable_qinvp();
  PROTOBUF_NODISCARD std::string* release_qinvp();
  void set_allocated_qinvp(std::string* qinvp);
  private:
  const std::string& _internal_qinvp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_qinvp(const std::string& value);
  std::string* _internal_mutable_qinvp();
  public:

  // string pInvQ = 13;
  void clear_pinvq();
  const std::string& pinvq() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_pinvq(ArgT0&& arg0, ArgT... args);
  std::string* mutable_pinvq();
  PROTOBUF_NODISCARD std::string* release_pinvq();
  void set_allocated_pinvq(std::string* pinvq);
  private:
  const std::string& _internal_pinvq() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pinvq(const std::string& value);
  std::string* _internal_mutable_pinvq();
  public:

  // @@protoc_insertion_point(class_scope:safeheron.proto.PailPriv)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr n_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr lambda_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mu_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr p_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr q_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr psqr_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr qsqr_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pminus1_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr qminus1_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr hp_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr hq_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr qinvp_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pinvq_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_paillier_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PailPub

// string n = 1;
inline void PailPub::clear_n() {
  n_.ClearToEmpty();
}
inline const std::string& PailPub::n() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.PailPub.n)
  return _internal_n();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PailPub::set_n(ArgT0&& arg0, ArgT... args) {
 
 n_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.PailPub.n)
}
inline std::string* PailPub::mutable_n() {
  std::string* _s = _internal_mutable_n();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.PailPub.n)
  return _s;
}
inline const std::string& PailPub::_internal_n() const {
  return n_.Get();
}
inline void PailPub::_internal_set_n(const std::string& value) {
  
  n_.Set(value, GetArenaForAllocation());
}
inline std::string* PailPub::_internal_mutable_n() {
  
  return n_.Mutable(GetArenaForAllocation());
}
inline std::string* PailPub::release_n() {
  // @@protoc_insertion_point(field_release:safeheron.proto.PailPub.n)
  return n_.Release();
}
inline void PailPub::set_allocated_n(std::string* n) {
  if (n != nullptr) {
    
  } else {
    
  }
  n_.SetAllocated(n, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (n_.IsDefault()) {
    n_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.PailPub.n)
}

// string g = 2;
inline void PailPub::clear_g() {
  g_.ClearToEmpty();
}
inline const std::string& PailPub::g() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.PailPub.g)
  return _internal_g();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PailPub::set_g(ArgT0&& arg0, ArgT... args) {
 
 g_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.PailPub.g)
}
inline std::string* PailPub::mutable_g() {
  std::string* _s = _internal_mutable_g();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.PailPub.g)
  return _s;
}
inline const std::string& PailPub::_internal_g() const {
  return g_.Get();
}
inline void PailPub::_internal_set_g(const std::string& value) {
  
  g_.Set(value, GetArenaForAllocation());
}
inline std::string* PailPub::_internal_mutable_g() {
  
  return g_.Mutable(GetArenaForAllocation());
}
inline std::string* PailPub::release_g() {
  // @@protoc_insertion_point(field_release:safeheron.proto.PailPub.g)
  return g_.Release();
}
inline void PailPub::set_allocated_g(std::string* g) {
  if (g != nullptr) {
    
  } else {
    
  }
  g_.SetAllocated(g, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (g_.IsDefault()) {
    g_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.PailPub.g)
}

// -------------------------------------------------------------------

// PailPriv

// string n = 1;
inline void PailPriv::clear_n() {
  n_.ClearToEmpty();
}
inline const std::string& PailPriv::n() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.PailPriv.n)
  return _internal_n();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PailPriv::set_n(ArgT0&& arg0, ArgT... args) {
 
 n_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.PailPriv.n)
}
inline std::string* PailPriv::mutable_n() {
  std::string* _s = _internal_mutable_n();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.PailPriv.n)
  return _s;
}
inline const std::string& PailPriv::_internal_n() const {
  return n_.Get();
}
inline void PailPriv::_internal_set_n(const std::string& value) {
  
  n_.Set(value, GetArenaForAllocation());
}
inline std::string* PailPriv::_internal_mutable_n() {
  
  return n_.Mutable(GetArenaForAllocation());
}
inline std::string* PailPriv::release_n() {
  // @@protoc_insertion_point(field_release:safeheron.proto.PailPriv.n)
  return n_.Release();
}
inline void PailPriv::set_allocated_n(std::string* n) {
  if (n != nullptr) {
    
  } else {
    
  }
  n_.SetAllocated(n, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (n_.IsDefault()) {
    n_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.PailPriv.n)
}

// string lambda = 2;
inline void PailPriv::clear_lambda() {
  lambda_.ClearToEmpty();
}
inline const std::string& PailPriv::lambda() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.PailPriv.lambda)
  return _internal_lambda();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PailPriv::set_lambda(ArgT0&& arg0, ArgT... args) {
 
 lambda_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.PailPriv.lambda)
}
inline std::string* PailPriv::mutable_lambda() {
  std::string* _s = _internal_mutable_lambda();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.PailPriv.lambda)
  return _s;
}
inline const std::string& PailPriv::_internal_lambda() const {
  return lambda_.Get();
}
inline void PailPriv::_internal_set_lambda(const std::string& value) {
  
  lambda_.Set(value, GetArenaForAllocation());
}
inline std::string* PailPriv::_internal_mutable_lambda() {
  
  return lambda_.Mutable(GetArenaForAllocation());
}
inline std::string* PailPriv::release_lambda() {
  // @@protoc_insertion_point(field_release:safeheron.proto.PailPriv.lambda)
  return lambda_.Release();
}
inline void PailPriv::set_allocated_lambda(std::string* lambda) {
  if (lambda != nullptr) {
    
  } else {
    
  }
  lambda_.SetAllocated(lambda, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (lambda_.IsDefault()) {
    lambda_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.PailPriv.lambda)
}

// string mu = 3;
inline void PailPriv::clear_mu() {
  mu_.ClearToEmpty();
}
inline const std::string& PailPriv::mu() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.PailPriv.mu)
  return _internal_mu();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PailPriv::set_mu(ArgT0&& arg0, ArgT... args) {
 
 mu_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.PailPriv.mu)
}
inline std::string* PailPriv::mutable_mu() {
  std::string* _s = _internal_mutable_mu();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.PailPriv.mu)
  return _s;
}
inline const std::string& PailPriv::_internal_mu() const {
  return mu_.Get();
}
inline void PailPriv::_internal_set_mu(const std::string& value) {
  
  mu_.Set(value, GetArenaForAllocation());
}
inline std::string* PailPriv::_internal_mutable_mu() {
  
  return mu_.Mutable(GetArenaForAllocation());
}
inline std::string* PailPriv::release_mu() {
  // @@protoc_insertion_point(field_release:safeheron.proto.PailPriv.mu)
  return mu_.Release();
}
inline void PailPriv::set_allocated_mu(std::string* mu) {
  if (mu != nullptr) {
    
  } else {
    
  }
  mu_.SetAllocated(mu, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (mu_.IsDefault()) {
    mu_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.PailPriv.mu)
}

// string p = 4;
inline void PailPriv::clear_p() {
  p_.ClearToEmpty();
}
inline const std::string& PailPriv::p() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.PailPriv.p)
  return _internal_p();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PailPriv::set_p(ArgT0&& arg0, ArgT... args) {
 
 p_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.PailPriv.p)
}
inline std::string* PailPriv::mutable_p() {
  std::string* _s = _internal_mutable_p();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.PailPriv.p)
  return _s;
}
inline const std::string& PailPriv::_internal_p() const {
  return p_.Get();
}
inline void PailPriv::_internal_set_p(const std::string& value) {
  
  p_.Set(value, GetArenaForAllocation());
}
inline std::string* PailPriv::_internal_mutable_p() {
  
  return p_.Mutable(GetArenaForAllocation());
}
inline std::string* PailPriv::release_p() {
  // @@protoc_insertion_point(field_release:safeheron.proto.PailPriv.p)
  return p_.Release();
}
inline void PailPriv::set_allocated_p(std::string* p) {
  if (p != nullptr) {
    
  } else {
    
  }
  p_.SetAllocated(p, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (p_.IsDefault()) {
    p_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.PailPriv.p)
}

// string q = 5;
inline void PailPriv::clear_q() {
  q_.ClearToEmpty();
}
inline const std::string& PailPriv::q() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.PailPriv.q)
  return _internal_q();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PailPriv::set_q(ArgT0&& arg0, ArgT... args) {
 
 q_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.PailPriv.q)
}
inline std::string* PailPriv::mutable_q() {
  std::string* _s = _internal_mutable_q();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.PailPriv.q)
  return _s;
}
inline const std::string& PailPriv::_internal_q() const {
  return q_.Get();
}
inline void PailPriv::_internal_set_q(const std::string& value) {
  
  q_.Set(value, GetArenaForAllocation());
}
inline std::string* PailPriv::_internal_mutable_q() {
  
  return q_.Mutable(GetArenaForAllocation());
}
inline std::string* PailPriv::release_q() {
  // @@protoc_insertion_point(field_release:safeheron.proto.PailPriv.q)
  return q_.Release();
}
inline void PailPriv::set_allocated_q(std::string* q) {
  if (q != nullptr) {
    
  } else {
    
  }
  q_.SetAllocated(q, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (q_.IsDefault()) {
    q_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.PailPriv.q)
}

// string pSqr = 6;
inline void PailPriv::clear_psqr() {
  psqr_.ClearToEmpty();
}
inline const std::string& PailPriv::psqr() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.PailPriv.pSqr)
  return _internal_psqr();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PailPriv::set_psqr(ArgT0&& arg0, ArgT... args) {
 
 psqr_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.PailPriv.pSqr)
}
inline std::string* PailPriv::mutable_psqr() {
  std::string* _s = _internal_mutable_psqr();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.PailPriv.pSqr)
  return _s;
}
inline const std::string& PailPriv::_internal_psqr() const {
  return psqr_.Get();
}
inline void PailPriv::_internal_set_psqr(const std::string& value) {
  
  psqr_.Set(value, GetArenaForAllocation());
}
inline std::string* PailPriv::_internal_mutable_psqr() {
  
  return psqr_.Mutable(GetArenaForAllocation());
}
inline std::string* PailPriv::release_psqr() {
  // @@protoc_insertion_point(field_release:safeheron.proto.PailPriv.pSqr)
  return psqr_.Release();
}
inline void PailPriv::set_allocated_psqr(std::string* psqr) {
  if (psqr != nullptr) {
    
  } else {
    
  }
  psqr_.SetAllocated(psqr, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (psqr_.IsDefault()) {
    psqr_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.PailPriv.pSqr)
}

// string qSqr = 7;
inline void PailPriv::clear_qsqr() {
  qsqr_.ClearToEmpty();
}
inline const std::string& PailPriv::qsqr() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.PailPriv.qSqr)
  return _internal_qsqr();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PailPriv::set_qsqr(ArgT0&& arg0, ArgT... args) {
 
 qsqr_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.PailPriv.qSqr)
}
inline std::string* PailPriv::mutable_qsqr() {
  std::string* _s = _internal_mutable_qsqr();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.PailPriv.qSqr)
  return _s;
}
inline const std::string& PailPriv::_internal_qsqr() const {
  return qsqr_.Get();
}
inline void PailPriv::_internal_set_qsqr(const std::string& value) {
  
  qsqr_.Set(value, GetArenaForAllocation());
}
inline std::string* PailPriv::_internal_mutable_qsqr() {
  
  return qsqr_.Mutable(GetArenaForAllocation());
}
inline std::string* PailPriv::release_qsqr() {
  // @@protoc_insertion_point(field_release:safeheron.proto.PailPriv.qSqr)
  return qsqr_.Release();
}
inline void PailPriv::set_allocated_qsqr(std::string* qsqr) {
  if (qsqr != nullptr) {
    
  } else {
    
  }
  qsqr_.SetAllocated(qsqr, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (qsqr_.IsDefault()) {
    qsqr_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.PailPriv.qSqr)
}

// string pMinus1 = 8;
inline void PailPriv::clear_pminus1() {
  pminus1_.ClearToEmpty();
}
inline const std::string& PailPriv::pminus1() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.PailPriv.pMinus1)
  return _internal_pminus1();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PailPriv::set_pminus1(ArgT0&& arg0, ArgT... args) {
 
 pminus1_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.PailPriv.pMinus1)
}
inline std::string* PailPriv::mutable_pminus1() {
  std::string* _s = _internal_mutable_pminus1();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.PailPriv.pMinus1)
  return _s;
}
inline const std::string& PailPriv::_internal_pminus1() const {
  return pminus1_.Get();
}
inline void PailPriv::_internal_set_pminus1(const std::string& value) {
  
  pminus1_.Set(value, GetArenaForAllocation());
}
inline std::string* PailPriv::_internal_mutable_pminus1() {
  
  return pminus1_.Mutable(GetArenaForAllocation());
}
inline std::string* PailPriv::release_pminus1() {
  // @@protoc_insertion_point(field_release:safeheron.proto.PailPriv.pMinus1)
  return pminus1_.Release();
}
inline void PailPriv::set_allocated_pminus1(std::string* pminus1) {
  if (pminus1 != nullptr) {
    
  } else {
    
  }
  pminus1_.SetAllocated(pminus1, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (pminus1_.IsDefault()) {
    pminus1_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.PailPriv.pMinus1)
}

// string qMinus1 = 9;
inline void PailPriv::clear_qminus1() {
  qminus1_.ClearToEmpty();
}
inline const std::string& PailPriv::qminus1() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.PailPriv.qMinus1)
  return _internal_qminus1();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PailPriv::set_qminus1(ArgT0&& arg0, ArgT... args) {
 
 qminus1_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.PailPriv.qMinus1)
}
inline std::string* PailPriv::mutable_qminus1() {
  std::string* _s = _internal_mutable_qminus1();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.PailPriv.qMinus1)
  return _s;
}
inline const std::string& PailPriv::_internal_qminus1() const {
  return qminus1_.Get();
}
inline void PailPriv::_internal_set_qminus1(const std::string& value) {
  
  qminus1_.Set(value, GetArenaForAllocation());
}
inline std::string* PailPriv::_internal_mutable_qminus1() {
  
  return qminus1_.Mutable(GetArenaForAllocation());
}
inline std::string* PailPriv::release_qminus1() {
  // @@protoc_insertion_point(field_release:safeheron.proto.PailPriv.qMinus1)
  return qminus1_.Release();
}
inline void PailPriv::set_allocated_qminus1(std::string* qminus1) {
  if (qminus1 != nullptr) {
    
  } else {
    
  }
  qminus1_.SetAllocated(qminus1, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (qminus1_.IsDefault()) {
    qminus1_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.PailPriv.qMinus1)
}

// string hp = 10;
inline void PailPriv::clear_hp() {
  hp_.ClearToEmpty();
}
inline const std::string& PailPriv::hp() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.PailPriv.hp)
  return _internal_hp();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PailPriv::set_hp(ArgT0&& arg0, ArgT... args) {
 
 hp_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.PailPriv.hp)
}
inline std::string* PailPriv::mutable_hp() {
  std::string* _s = _internal_mutable_hp();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.PailPriv.hp)
  return _s;
}
inline const std::string& PailPriv::_internal_hp() const {
  return hp_.Get();
}
inline void PailPriv::_internal_set_hp(const std::string& value) {
  
  hp_.Set(value, GetArenaForAllocation());
}
inline std::string* PailPriv::_internal_mutable_hp() {
  
  return hp_.Mutable(GetArenaForAllocation());
}
inline std::string* PailPriv::release_hp() {
  // @@protoc_insertion_point(field_release:safeheron.proto.PailPriv.hp)
  return hp_.Release();
}
inline void PailPriv::set_allocated_hp(std::string* hp) {
  if (hp != nullptr) {
    
  } else {
    
  }
  hp_.SetAllocated(hp, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (hp_.IsDefault()) {
    hp_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.PailPriv.hp)
}

// string hq = 11;
inline void PailPriv::clear_hq() {
  hq_.ClearToEmpty();
}
inline const std::string& PailPriv::hq() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.PailPriv.hq)
  return _internal_hq();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PailPriv::set_hq(ArgT0&& arg0, ArgT... args) {
 
 hq_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.PailPriv.hq)
}
inline std::string* PailPriv::mutable_hq() {
  std::string* _s = _internal_mutable_hq();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.PailPriv.hq)
  return _s;
}
inline const std::string& PailPriv::_internal_hq() const {
  return hq_.Get();
}
inline void PailPriv::_internal_set_hq(const std::string& value) {
  
  hq_.Set(value, GetArenaForAllocation());
}
inline std::string* PailPriv::_internal_mutable_hq() {
  
  return hq_.Mutable(GetArenaForAllocation());
}
inline std::string* PailPriv::release_hq() {
  // @@protoc_insertion_point(field_release:safeheron.proto.PailPriv.hq)
  return hq_.Release();
}
inline void PailPriv::set_allocated_hq(std::string* hq) {
  if (hq != nullptr) {
    
  } else {
    
  }
  hq_.SetAllocated(hq, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (hq_.IsDefault()) {
    hq_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.PailPriv.hq)
}

// string qInvP = 12;
inline void PailPriv::clear_qinvp() {
  qinvp_.ClearToEmpty();
}
inline const std::string& PailPriv::qinvp() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.PailPriv.qInvP)
  return _internal_qinvp();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PailPriv::set_qinvp(ArgT0&& arg0, ArgT... args) {
 
 qinvp_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.PailPriv.qInvP)
}
inline std::string* PailPriv::mutable_qinvp() {
  std::string* _s = _internal_mutable_qinvp();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.PailPriv.qInvP)
  return _s;
}
inline const std::string& PailPriv::_internal_qinvp() const {
  return qinvp_.Get();
}
inline void PailPriv::_internal_set_qinvp(const std::string& value) {
  
  qinvp_.Set(value, GetArenaForAllocation());
}
inline std::string* PailPriv::_internal_mutable_qinvp() {
  
  return qinvp_.Mutable(GetArenaForAllocation());
}
inline std::string* PailPriv::release_qinvp() {
  // @@protoc_insertion_point(field_release:safeheron.proto.PailPriv.qInvP)
  return qinvp_.Release();
}
inline void PailPriv::set_allocated_qinvp(std::string* qinvp) {
  if (qinvp != nullptr) {
    
  } else {
    
  }
  qinvp_.SetAllocated(qinvp, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (qinvp_.IsDefault()) {
    qinvp_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.PailPriv.qInvP)
}

// string pInvQ = 13;
inline void PailPriv::clear_pinvq() {
  pinvq_.ClearToEmpty();
}
inline const std::string& PailPriv::pinvq() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.PailPriv.pInvQ)
  return _internal_pinvq();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PailPriv::set_pinvq(ArgT0&& arg0, ArgT... args) {
 
 pinvq_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:safeheron.proto.PailPriv.pInvQ)
}
inline std::string* PailPriv::mutable_pinvq() {
  std::string* _s = _internal_mutable_pinvq();
  // @@protoc_insertion_point(field_mutable:safeheron.proto.PailPriv.pInvQ)
  return _s;
}
inline const std::string& PailPriv::_internal_pinvq() const {
  return pinvq_.Get();
}
inline void PailPriv::_internal_set_pinvq(const std::string& value) {
  
  pinvq_.Set(value, GetArenaForAllocation());
}
inline std::string* PailPriv::_internal_mutable_pinvq() {
  
  return pinvq_.Mutable(GetArenaForAllocation());
}
inline std::string* PailPriv::release_pinvq() {
  // @@protoc_insertion_point(field_release:safeheron.proto.PailPriv.pInvQ)
  return pinvq_.Release();
}
inline void PailPriv::set_allocated_pinvq(std::string* pinvq) {
  if (pinvq != nullptr) {
    
  } else {
    
  }
  pinvq_.SetAllocated(pinvq, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (pinvq_.IsDefault()) {
    pinvq_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.PailPriv.pInvQ)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace safeheron

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_paillier_2eproto
