// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: curve_point.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_curve_5fpoint_2eproto_MULTI_VERSION
#define GOOGLE_PROTOBUF_INCLUDED_curve_5fpoint_2eproto_MULTI_VERSION

#include <google/protobuf/port_def.inc>

#if PROTOBUF_VERSION >= 3014000 && 3014000 >= PROTOBUF_MIN_PROTOC_VERSION
#include <google/protobuf/port_undef.inc>
#include "3_14/curve_point.pb.h"
#elif PROTOBUF_VERSION >= 3020000 && 3020000 >= PROTOBUF_MIN_PROTOC_VERSION
#include <google/protobuf/port_undef.inc>
#include "3_20/curve_point.pb.h"
#else
#include <google/protobuf/port_undef.inc>
#error Invalid version of protobuf.
#endif

#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_curve_5fpoint_2eproto_MULTI_VERSION
