// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: curve_point.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_curve_5fpoint_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_curve_5fpoint_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_curve_5fpoint_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_curve_5fpoint_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_curve_5fpoint_2eproto;
namespace safeheron {
namespace proto {
class CurvePoint;
class CurvePointDefaultTypeInternal;
extern CurvePointDefaultTypeInternal _CurvePoint_default_instance_;
}  // namespace proto
}  // namespace safeheron
PROTOBUF_NAMESPACE_OPEN
template<> ::safeheron::proto::CurvePoint* Arena::CreateMaybeMessage<::safeheron::proto::CurvePoint>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace safeheron {
namespace proto {

// ===================================================================

class CurvePoint PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.CurvePoint) */ {
 public:
  inline CurvePoint() : CurvePoint(nullptr) {}
  virtual ~CurvePoint();

  CurvePoint(const CurvePoint& from);
  CurvePoint(CurvePoint&& from) noexcept
    : CurvePoint() {
    *this = ::std::move(from);
  }

  inline CurvePoint& operator=(const CurvePoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline CurvePoint& operator=(CurvePoint&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CurvePoint& default_instance();

  static inline const CurvePoint* internal_default_instance() {
    return reinterpret_cast<const CurvePoint*>(
               &_CurvePoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CurvePoint& a, CurvePoint& b) {
    a.Swap(&b);
  }
  inline void Swap(CurvePoint* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CurvePoint* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CurvePoint* New() const final {
    return CreateMaybeMessage<CurvePoint>(nullptr);
  }

  CurvePoint* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CurvePoint>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CurvePoint& from);
  void MergeFrom(const CurvePoint& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CurvePoint* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "safeheron.proto.CurvePoint";
  }
  protected:
  explicit CurvePoint(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_curve_5fpoint_2eproto);
    return ::descriptor_table_curve_5fpoint_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kCurveFieldNumber = 3,
  };
  // string x = 1;
  void clear_x();
  const std::string& x() const;
  void set_x(const std::string& value);
  void set_x(std::string&& value);
  void set_x(const char* value);
  void set_x(const char* value, size_t size);
  std::string* mutable_x();
  std::string* release_x();
  void set_allocated_x(std::string* x);
  private:
  const std::string& _internal_x() const;
  void _internal_set_x(const std::string& value);
  std::string* _internal_mutable_x();
  public:

  // string y = 2;
  void clear_y();
  const std::string& y() const;
  void set_y(const std::string& value);
  void set_y(std::string&& value);
  void set_y(const char* value);
  void set_y(const char* value, size_t size);
  std::string* mutable_y();
  std::string* release_y();
  void set_allocated_y(std::string* y);
  private:
  const std::string& _internal_y() const;
  void _internal_set_y(const std::string& value);
  std::string* _internal_mutable_y();
  public:

  // string curve = 3;
  void clear_curve();
  const std::string& curve() const;
  void set_curve(const std::string& value);
  void set_curve(std::string&& value);
  void set_curve(const char* value);
  void set_curve(const char* value, size_t size);
  std::string* mutable_curve();
  std::string* release_curve();
  void set_allocated_curve(std::string* curve);
  private:
  const std::string& _internal_curve() const;
  void _internal_set_curve(const std::string& value);
  std::string* _internal_mutable_curve();
  public:

  // @@protoc_insertion_point(class_scope:safeheron.proto.CurvePoint)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr x_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr y_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr curve_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_curve_5fpoint_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CurvePoint

// string x = 1;
inline void CurvePoint::clear_x() {
  x_.ClearToEmpty();
}
inline const std::string& CurvePoint::x() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.CurvePoint.x)
  return _internal_x();
}
inline void CurvePoint::set_x(const std::string& value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:safeheron.proto.CurvePoint.x)
}
inline std::string* CurvePoint::mutable_x() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.CurvePoint.x)
  return _internal_mutable_x();
}
inline const std::string& CurvePoint::_internal_x() const {
  return x_.Get();
}
inline void CurvePoint::_internal_set_x(const std::string& value) {
  
  x_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void CurvePoint::set_x(std::string&& value) {
  
  x_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.CurvePoint.x)
}
inline void CurvePoint::set_x(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  x_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:safeheron.proto.CurvePoint.x)
}
inline void CurvePoint::set_x(const char* value,
    size_t size) {
  
  x_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.CurvePoint.x)
}
inline std::string* CurvePoint::_internal_mutable_x() {
  
  return x_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* CurvePoint::release_x() {
  // @@protoc_insertion_point(field_release:safeheron.proto.CurvePoint.x)
  return x_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CurvePoint::set_allocated_x(std::string* x) {
  if (x != nullptr) {
    
  } else {
    
  }
  x_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), x,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.CurvePoint.x)
}

// string y = 2;
inline void CurvePoint::clear_y() {
  y_.ClearToEmpty();
}
inline const std::string& CurvePoint::y() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.CurvePoint.y)
  return _internal_y();
}
inline void CurvePoint::set_y(const std::string& value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:safeheron.proto.CurvePoint.y)
}
inline std::string* CurvePoint::mutable_y() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.CurvePoint.y)
  return _internal_mutable_y();
}
inline const std::string& CurvePoint::_internal_y() const {
  return y_.Get();
}
inline void CurvePoint::_internal_set_y(const std::string& value) {
  
  y_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void CurvePoint::set_y(std::string&& value) {
  
  y_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.CurvePoint.y)
}
inline void CurvePoint::set_y(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  y_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:safeheron.proto.CurvePoint.y)
}
inline void CurvePoint::set_y(const char* value,
    size_t size) {
  
  y_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.CurvePoint.y)
}
inline std::string* CurvePoint::_internal_mutable_y() {
  
  return y_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* CurvePoint::release_y() {
  // @@protoc_insertion_point(field_release:safeheron.proto.CurvePoint.y)
  return y_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CurvePoint::set_allocated_y(std::string* y) {
  if (y != nullptr) {
    
  } else {
    
  }
  y_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), y,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.CurvePoint.y)
}

// string curve = 3;
inline void CurvePoint::clear_curve() {
  curve_.ClearToEmpty();
}
inline const std::string& CurvePoint::curve() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.CurvePoint.curve)
  return _internal_curve();
}
inline void CurvePoint::set_curve(const std::string& value) {
  _internal_set_curve(value);
  // @@protoc_insertion_point(field_set:safeheron.proto.CurvePoint.curve)
}
inline std::string* CurvePoint::mutable_curve() {
  // @@protoc_insertion_point(field_mutable:safeheron.proto.CurvePoint.curve)
  return _internal_mutable_curve();
}
inline const std::string& CurvePoint::_internal_curve() const {
  return curve_.Get();
}
inline void CurvePoint::_internal_set_curve(const std::string& value) {
  
  curve_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void CurvePoint::set_curve(std::string&& value) {
  
  curve_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.CurvePoint.curve)
}
inline void CurvePoint::set_curve(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  curve_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:safeheron.proto.CurvePoint.curve)
}
inline void CurvePoint::set_curve(const char* value,
    size_t size) {
  
  curve_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.CurvePoint.curve)
}
inline std::string* CurvePoint::_internal_mutable_curve() {
  
  return curve_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* CurvePoint::release_curve() {
  // @@protoc_insertion_point(field_release:safeheron.proto.CurvePoint.curve)
  return curve_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CurvePoint::set_allocated_curve(std::string* curve) {
  if (curve != nullptr) {
    
  } else {
    
  }
  curve_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), curve,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.CurvePoint.curve)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace safeheron

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_curve_5fpoint_2eproto
